@echo off
echo Iniciando PhishGuard API...
cd /d "c:\Users\Kaio vittor\Documents\PhishGuard-API\PhishGuard-API\back"
echo Instalando dependencias se necessario...
"C:/Users/Kaio vittor/Documents/PhishGuard-API/PhishGuard-API/.venv/Scripts/pip.exe" install pydantic-settings
echo Iniciando servidor...
"C:/Users/Kaio vittor/Documents/PhishGuard-API/PhishGuard-API/.venv/Scripts/uvicorn.exe" main:app --host 0.0.0.0 --port 8000 --reload
pause
